### ISSUE TITLE
com.sun.ts.tests.jsonp.pluggability.jsonprovidertests.Client.jsonProviderTest10 failes with NPE

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/jakartaee-tck#1002]
**Describe the bug**
Attempting to create a parser with a null input stream is throwing an NPE rather than the expected JsonException.

**To Reproduce**
Run the current tck runner and this error is seen:
```
05-16-2022 14:04:39:  SVR-ERROR: java.lang.NullPointerException: Cannot invoke "java.io.InputStream.read()" because "this.in" is null
	at org.eclipse.parsson.UnicodeDetectingInputStream.fillBuf(UnicodeDetectingInputStream.java:65)
	at org.eclipse.parsson.UnicodeDetectingInputStream.detectEncoding(UnicodeDetectingInputStream.java:104)
	at org.eclipse.parsson.UnicodeDetectingInputStream.<init>(UnicodeDetectingInputStream.java:51)
	at org.eclipse.parsson.JsonParserImpl.<init>(JsonParserImpl.java:87)
	at org.eclipse.parsson.JsonParserImpl.<init>(JsonParserImpl.java:80)
	at org.eclipse.parsson.JsonProviderImpl.createParser(JsonProviderImpl.java:64)
	at jakarta.json.Json.createParser(Json.java:88)
	at com.sun.ts.tests.jsonp.pluggability.jsonprovidertests.Client.jsonProviderTest10(Client.java:342)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.sun.ts.lib.harness.EETest.run(EETest.java:596)
	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:115)
	at com.sun.ts.tests.common.vehicle.ejb.EJBVehicle.runTest(EJBVehicle.java:74)
```

**Expected behavior**
The test is expecting a JsonException

Either the implementation is incorrect or the spec has changed, but all I see is this javadoc from the 2.1.0 

```
    /**
     * Creates a JSON parser from the specified byte stream.
     * The character encoding of the stream is determined
     * as defined in <a href="http://tools.ietf.org/rfc/rfc7159.txt">RFC 7159
     * </a>.
     *
     * @param in i/o stream from which JSON is to be read
     * @throws JsonException if encoding cannot be determined
     *         or i/o error (IOException would be cause of JsonException)
     * @return a JSON parser
     */
    public abstract JsonParser createParser(InputStream in);
```

**Comment by scottmarlow** [comment]
Closing as I think this is resolved.  Please reopen if needed.
