### ISSUE TITLE
com.sun.ts.tests.jsonp.pluggability.jsonprovidertests.Client.jsonProviderTest1 Fails to load MyJsonProvider

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/jakartaee-tck#1003]
**Describe the bug**
It looks like the com.sun.ts.tests.jsonp.provider.MyJsonProvider is not seen as the service for jakarta.json.spi.JsonProvider service class.

**To Reproduce**
Run the TCK:
```
05-16-2022 14:04:20:  SVR-ERROR: com.sun.ts.lib.harness.EETest$Fault: jsonProviderTest1 Failed
	at com.sun.ts.tests.jsonp.pluggability.jsonprovidertests.Client.jsonProviderTest1(Client.java:115)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.sun.ts.lib.harness.EETest.run(EETest.java:596)
	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:115)
	at com.sun.ts.tests.common.vehicle.ejb.EJBVehicle.runTest(EJBVehicle.java:74)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.glassfish.ejb.security.application.EJBSecurityManager$1.run(EJBSecurityManager.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at org.glassfish.ejb.security.application.EJBSecurityManager.lambda$doAsPrivileged$5(EJBSecurityManager.java:392)
	at org.glassfish.exousia.AuthorizationService.runInScope(AuthorizationService.java:577)
	at org.glassfish.ejb.security.application.EJBSecurityManager.doAsPrivileged(EJBSecurityManager.java:392)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:306)
	at com.sun.ejb.containers.BaseContainer.invokeTargetBeanMethod(BaseContainer.java:3711)
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4224)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4206)
	at com.sun.ejb.containers.EJBObjectInvocationHandler.invoke(EJBObjectInvocationHandler.java:173)
	at com.sun.ejb.containers.EJBObjectInvocationHandler.invoke(EJBObjectInvocationHandler.java:91)
```

**Expected behavior**
The com.sun.ts.tests.jsonp.provider.MyJsonProvider class should be seen as the JsonProvider.

**Comment by gurunrao** [comment]
reference bug at GF for the same pluggability failures - https://github.com/eclipse-ee4j/glassfish/issues/23892

**Comment by scottmarlow** [comment]
I just asked on https://github.com/eclipse-ee4j/glassfish/issues/23892#issuecomment-1130406265 if this failure can occur for other Jakarta EE 10 implementations or only those that have [org.glassfish.hk2.osgiresourcelocator.ServiceLoader](https://github.com/eclipse-ee4j/jsonp/blob/master/api/src/main/java/jakarta/json/spi/JsonProvider.java#L587).  Mentioning here for those following this issue.
