### ISSUE TITLE
Challenges for tests com/sun/ts/tests/ejb30/lite/packaging/war/datasource/singleton/JsfClient.java 

### ISSUE THREAD

**Issue by chengfang** [eclipse-ee4j/jakartaee-tck#1060]
1. The relevant specification version and section number(s). Jakarta EE 10 Core Profile, 5.18.3. DataSource Resource Definition
https://jakarta.ee/specifications/platform/9.1/jakarta-platform-spec-9.1.html#a1688

2. The coordinates of the challenged test(s). all tests in com/sun/ts/tests/ejb30/lite/packaging/war/datasource/singleton/JsfClient.java 

4. The exact TCK version. Jakarta EE 10 Core Profile TCK

6. The implementation being tested, including name and company. WildFly 27 Preview, Red Hat

8. A full description of why the test is invalid and what the correct behavior is believed to be.
9. Any supporting material; debug logs, test output (.jtr file), test logs, run scripts, etc.

Tests in com/sun/ts/tests/ejb30/lite/packaging/war/datasource/singleton directory contain both Client.java.template and JsfClient.java.template, which define the same set of data source definitions. This caused conflict registering multiple data sources under the same jndi name in the same namespace, when testing with WildFly 27 Preview.

The jsfclient file needs to be fixed to use different name attributes for the 2 data source definitions:

```java
@DataSourceDefinition(name="java:comp/env/compds",
        className="@className@",
... 
),
@DataSourceDefinition(name="java:comp/env/compds2",
        className="@className@",
        portNumber=@portNumber@,
... 
```

Error messages:
```
2022-06-08 01:27:13,716 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-1) MSC000001: Failed to start service jboss.deployment.unit."ejblite_packaging_war_datasource_singleton_ejblitejsf_vehicle_web.war".INSTALL: org.jboss.msc.service.StartException in service jboss.deployment.unit."ejblite_packaging_war_datasource_singleton_ejblitejsf_vehicle_web.war".INSTALL: WFLYSRV0153: Failed to process phase INSTALL of deployment "ejblite_packaging_war_datasource_singleton_ejblitejsf_vehicle_web.war"
        at org.jboss.as.server@19.0.0.Beta11//org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:189)
        at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1739)
        at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1701)
        at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: org.jboss.msc.service.DuplicateServiceException: Service jboss.data-source."jboss.naming.context.java.module.ejblite_packaging_war_datasource_singleton_ejblitejsf_vehicle_web.ejblite_packaging_war_datasource_singleton_ejblitejsf_vehicle_web.env.compds2" is already registered
        at org.jboss.as.connector@27.0.0.Alpha2-SNAPSHOT//org.jboss.as.connector.deployers.datasource.DataSourceDefinitionInjectionSource.getResourceValue(DataSourceDefinitionInjectionSource.java:178)
        at org.jboss.as.ee@27.0.0.Alpha2-SNAPSHOT//org.jboss.as.ee.component.deployers.ModuleJndiBindingProcessor.addJndiBinding(ModuleJndiBindingProcessor.java:271)
        at org.jboss.as.ee@27.0.0.Alpha2-SNAPSHOT//org.jboss.as.ee.component.deployers.ModuleJndiBindingProcessor.deploy(ModuleJndiBindingProcessor.java:202)
        at org.jboss.as.server@19.0.0.Beta11//org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:182)
        ... 8 more
Caused by: org.jboss.msc.service.DuplicateServiceException: Service jboss.data-source."jboss.naming.context.java.module.ejblite_packaging_war_datasource_singleton_ejblitejsf_vehicle_web.ejblite_packaging_war_datasource_singleton_ejblitejsf_vehicle_web.env.compds2" is already registered
        at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceRegistrationImpl.set(ServiceRegistrationImpl.java:135)
        at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl.startInstallation(ServiceControllerImpl.java:243)
        at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceContainerImpl.install(ServiceContainerImpl.java:758)
        at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceTargetImpl.install(ServiceTargetImpl.java:260)
        at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$ChildServiceTarget.install(ServiceControllerImpl.java:2065)
        at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceTargetImpl.install(ServiceTargetImpl.java:260)
        at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$ChildServiceTarget.install(ServiceControllerImpl.java:2065)
        at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceBuilderImpl.install(ServiceBuilderImpl.java:192)
        at org.jboss.as.connector@27.0.0.Alpha2-SNAPSHOT//org.jboss.as.connector.deployers.datasource.DataSourceDefinitionInjectionSource.startDataSource(DataSourceDefinitionInjectionSource.java:294)
        at org.jboss.as.connector@27.0.0.Alpha2-SNAPSHOT//org.jboss.as.connector.deployers.datasource.DataSourceDefinitionInjectionSource.getResourceValue(DataSourceDefinitionInjectionSource.java:174)
        ... 11 more
```

**Comment by scottmarlow** [comment]
We can look at updating the JsfClient to update the DataSourceDefinition name as all of the other test sources in that test package, use unique names I think.

**Comment by scottmarlow** [comment]
https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck-scottmarlow/job/issue_1060/2/ is building the Platform TCK and running the ejb30/lite/packaging/war/datasource/singleton tests with a small change to use unique DataSourceDefinition names in JsfClient
