### ISSUE TITLE
ejb30/timer/schedule/lifecycle/Client.java#timerEquals failed when timer already expired

### ISSUE THREAD

**Issue by chengfang** [eclipse-ee4j/jakartaee-tck#124]
This test (com/sun/ts/tests/ejb30/timer/schedule/lifecycle/Client.java#timerEquals_from_ejbliteservlet) may fail when the timer already expired when the test tries to cancel it.

It failed because the test tries to cancel a timer that has already expired in this test run, which results in javax.ejb.NoSuchObjectLocalException.  This is correct on the ejb container side.  

The test should be updated to handle this exception by ignoring it since this is part of cleanup after the main test logic for this test. 

The error when running with WildFly:

```
[javatest.batch] [TEST FAILED] testName=timerEquals 
[javatest.batch] 
[javatest.batch] Compare timer to itself. Got the expected result:[id=3c8fc544-fb7f-45f0-a435-dc8d128dcfd2 timedObjectId=ejb30_timer_schedule_lifecycle_ejbliteservlet_vehicle_web.ejb30_timer_schedule_lifecycle_ejbliteservlet_vehicle_web.ScheduleBean auto-timer?:false persistent?:true timerService=org.jboss.as.ejb3.timerservice.TimerServiceImpl@75e81342 initialExpiration=null intervalDuration(in milli sec)=0 nextExpiration=Wed Sep 11 23:31:45 EDT 2019 timerState=ACTIVE info=TimerInfo testName=timerEqualst1 testNumber=0 status=false doubleVar=0.0 longVar=0 charVar=  booleanVar=false intVar=0] ScheduleExpression [second=45;minute=31;hour=23;dayOfMonth=11;month=9;dayOfWeek=*;year=2019;timezoneID=null;start=null;end=null]	
[javatest.batch] 
[javatest.batch] Compare timer to t1Found. Got the expected result:[id=3c8fc544-fb7f-45f0-a435-dc8d128dcfd2 timedObjectId=ejb30_timer_schedule_lifecycle_ejbliteservlet_vehicle_web.ejb30_timer_schedule_lifecycle_ejbliteservlet_vehicle_web.ScheduleBean auto-timer?:false persistent?:true timerService=org.jboss.as.ejb3.timerservice.TimerServiceImpl@75e81342 initialExpiration=null intervalDuration(in milli sec)=0 nextExpiration=Wed Sep 11 23:31:45 EDT 2019 timerState=ACTIVE info=TimerInfo testName=timerEqualst1 testNumber=0 status=false doubleVar=0.0 longVar=0 charVar=  booleanVar=false intVar=0] ScheduleExpression [second=45;minute=31;hour=23;dayOfMonth=11;month=9;dayOfWeek=*;year=2019;timezoneID=null;start=null;end=null]	
[javatest.batch] Compare timer to null. Got the expected NotEquals result. compareTo:[id=3c8fc544-fb7f-45f0-a435-dc8d128dcfd2 timedObjectId=ejb30_timer_schedule_lifecycle_ejbliteservlet_vehicle_web.ejb30_timer_schedule_lifecycle_ejbliteservlet_vehicle_web.ScheduleBean auto-timer?:false persistent?:true timerService=org.jboss.as.ejb3.timerservice.TimerServiceImpl@75e81342 initialExpiration=null intervalDuration(in milli sec)=0 nextExpiration=Wed Sep 11 23:31:45 EDT 2019 timerState=ACTIVE info=TimerInfo testName=timerEqualst1 testNumber=0 status=false doubleVar=0.0 longVar=0 charVar=  booleanVar=false intVar=0] ScheduleExpression [second=45;minute=31;hour=23;dayOfMonth=11;month=9;dayOfWeek=*;year=2019;timezoneID=null;start=null;end=null], actual:null	
[javatest.batch] Compare timer to 1. Got the expected NotEquals result. compareTo:[id=3c8fc544-fb7f-45f0-a435-dc8d128dcfd2 timedObjectId=ejb30_timer_schedule_lifecycle_ejbliteservlet_vehicle_web.ejb30_timer_schedule_lifecycle_ejbliteservlet_vehicle_web.ScheduleBean auto-timer?:false persistent?:true timerService=org.jboss.as.ejb3.timerservice.TimerServiceImpl@75e81342 initialExpiration=null intervalDuration(in milli sec)=0 nextExpiration=Wed Sep 11 23:31:45 EDT 2019 timerState=ACTIVE info=TimerInfo testName=timerEqualst1 testNumber=0 status=false doubleVar=0.0 longVar=0 charVar=  booleanVar=false intVar=0] ScheduleExpression [second=45;minute=31;hour=23;dayOfMonth=11;month=9;dayOfWeek=*;year=2019;timezoneID=null;start=null;end=null], actual:1	
[javatest.batch] Compare timer to true. Got the expected NotEquals result. compareTo:[id=3c8fc544-fb7f-45f0-a435-dc8d128dcfd2 timedObjectId=ejb30_timer_schedule_lifecycle_ejbliteservlet_vehicle_web.ejb30_timer_schedule_lifecycle_ejbliteservlet_vehicle_web.ScheduleBean auto-timer?:false persistent?:true timerService=org.jboss.as.ejb3.timerservice.TimerServiceImpl@75e81342 initialExpiration=null intervalDuration(in milli sec)=0 nextExpiration=Wed Sep 11 23:31:45 EDT 2019 timerState=ACTIVE info=TimerInfo testName=timerEqualst1 testNumber=0 status=false doubleVar=0.0 longVar=0 charVar=  booleanVar=false intVar=0] ScheduleExpression [second=45;minute=31;hour=23;dayOfMonth=11;month=9;dayOfWeek=*;year=2019;timezoneID=null;start=null;end=null], actual:true	
[javatest.batch] Compare timer to TimerHandle. Got the expected NotEquals result. compareTo:[id=3c8fc544-fb7f-45f0-a435-dc8d128dcfd2 timedObjectId=ejb30_timer_schedule_lifecycle_ejbliteservlet_vehicle_web.ejb30_timer_schedule_lifecycle_ejbliteservlet_vehicle_web.ScheduleBean auto-timer?:false persistent?:true timerService=org.jboss.as.ejb3.timerservice.TimerServiceImpl@75e81342 initialExpiration=null intervalDuration(in milli sec)=0 nextExpiration=Wed Sep 11 23:31:45 EDT 2019 timerState=ACTIVE info=TimerInfo testName=timerEqualst1 testNumber=0 status=false doubleVar=0.0 longVar=0 charVar=  booleanVar=false intVar=0] ScheduleExpression [second=45;minute=31;hour=23;dayOfMonth=11;month=9;dayOfWeek=*;year=2019;timezoneID=null;start=null;end=null], actual:org.jboss.as.ejb3.timerservice.TimerHandleImpl@8dee6604	
[javatest.batch] Compare TimerHandle to timer. Got the expected NotEquals result. compareTo:org.jboss.as.ejb3.timerservice.TimerHandleImpl@8dee6604, actual:[id=3c8fc544-fb7f-45f0-a435-dc8d128dcfd2 timedObjectId=ejb30_timer_schedule_lifecycle_ejbliteservlet_vehicle_web.ejb30_timer_schedule_lifecycle_ejbliteservlet_vehicle_web.ScheduleBean auto-timer?:false persistent?:true timerService=org.jboss.as.ejb3.timerservice.TimerServiceImpl@75e81342 initialExpiration=null intervalDuration(in milli sec)=0 nextExpiration=Wed Sep 11 23:31:45 EDT 2019 timerState=ACTIVE info=TimerInfo testName=timerEqualst1 testNumber=0 status=false doubleVar=0.0 longVar=0 charVar=  booleanVar=false intVar=0] ScheduleExpression [second=45;minute=31;hour=23;dayOfMonth=11;month=9;dayOfWeek=*;year=2019;timezoneID=null;start=null;end=null]	
[javatest.batch] Compare 2 timers. Got the expected NotEquals result. compareTo:[id=3c8fc544-fb7f-45f0-a435-dc8d128dcfd2 timedObjectId=ejb30_timer_schedule_lifecycle_ejbliteservlet_vehicle_web.ejb30_timer_schedule_lifecycle_ejbliteservlet_vehicle_web.ScheduleBean auto-timer?:false persistent?:true timerService=org.jboss.as.ejb3.timerservice.TimerServiceImpl@75e81342 initialExpiration=null intervalDuration(in milli sec)=0 nextExpiration=Wed Sep 11 23:31:45 EDT 2019 timerState=ACTIVE info=TimerInfo testName=timerEqualst1 testNumber=0 status=false doubleVar=0.0 longVar=0 charVar=  booleanVar=false intVar=0] ScheduleExpression [second=45;minute=31;hour=23;dayOfMonth=11;month=9;dayOfWeek=*;year=2019;timezoneID=null;start=null;end=null], actual:[id=2a61a3bd-a8f7-432b-aa85-1b3f98d25b76 timedObjectId=ejb30_timer_schedule_lifecycle_ejbliteservlet_vehicle_web.ejb30_timer_schedule_lifecycle_ejbliteservlet_vehicle_web.ScheduleBean auto-timer?:false persistent?:true timerService=org.jboss.as.ejb3.timerservice.TimerServiceImpl@75e81342 initialExpiration=null intervalDuration(in milli sec)=0 nextExpiration=Sat Sep 11 23:31:44 EDT 2021 timerState=ACTIVE info=TimerInfo testName=timerEquals testNumber=0 status=false doubleVar=0.0 longVar=0 charVar=  booleanVar=false intVar=0] ScheduleExpression [second=44;minute=31;hour=23;dayOfMonth=11;month=9;dayOfWeek=*;year=2021;timezoneID=null;start=null;end=null]	
[javatest.batch] Compare timer 3 to timer 4. Got the expected NotEquals result. compareTo:[id=eb1e9bde-3bfe-4944-9e53-1ec9ca1305ed timedObjectId=ejb30_timer_schedule_lifecycle_ejbliteservlet_vehicle_web.ejb30_timer_schedule_lifecycle_ejbliteservlet_vehicle_web.ScheduleBean auto-timer?:false persistent?:true timerService=org.jboss.as.ejb3.timerservice.TimerServiceImpl@75e81342 initialExpiration=null intervalDuration(in milli sec)=0 nextExpiration=Thu Sep 12 00:00:00 EDT 2019 timerState=ACTIVE info=TimerInfo testName=timerEquals testNumber=0 status=false doubleVar=0.0 longVar=0 charVar=  booleanVar=false intVar=0] ScheduleExpression [second=0;minute=0;hour=0;dayOfMonth=*;month=*;dayOfWeek=*;year=*;timezoneID=null;start=null;end=null], actual:[id=739aae2c-8305-47fa-b66e-d24edeccf675 timedObjectId=ejb30_timer_schedule_lifecycle_ejbliteservlet_vehicle_web.ejb30_timer_schedule_lifecycle_ejbliteservlet_vehicle_web.ScheduleBean auto-timer?:false persistent?:true timerService=org.jboss.as.ejb3.timerservice.TimerServiceImpl@75e81342 initialExpiration=null intervalDuration(in milli sec)=0 nextExpiration=Thu Sep 12 00:00:00 EDT 2019 timerState=ACTIVE info=TimerInfo testName=timerEquals testNumber=0 status=false doubleVar=0.0 longVar=0 charVar=  booleanVar=false intVar=0] ScheduleExpression [second=0;minute=0;hour=0;dayOfMonth=*;month=*;dayOfWeek=*;year=*;timezoneID=null;start=null;end=null]	Failed with exception 
[javatest.batch] javax.ejb.NoSuchObjectLocalException: WFLYEJB0330: Timer has expired
[javatest.batch] 	at org.jboss.as.ejb3.timerservice.TimerImpl.assertTimerState(TimerImpl.java:476)
[javatest.batch] 	at org.jboss.as.ejb3.timerservice.TimerServiceImpl.cancelTimer(TimerServiceImpl.java:636)
[javatest.batch] 	at org.jboss.as.ejb3.timerservice.TimerImpl.cancel(TimerImpl.java:164)
[javatest.batch] 	at com.sun.ts.tests.ejb30.timer.common.TimerBeanBaseWithoutTimeOutMethod.cancelTimer(TimerBeanBaseWithoutTimeOutMethod.java:95)

```

**Comment by chengfang** [comment]
This test may fail earlier than the step that tries to cancel the timers.  For example, it failed at the following step:

`assertNotEquals("Compare timer to TimerHandle.", t1, scheduleBean.getTimerHandle(t1));`

Since `t1` already expired at this step, so calling any timer method on it within `ScheduleBean` results in
```
javax.ejb.NoSuchObjectLocalException: WFLYEJB0330: Timer has expired
at org.jboss.as.ejb3.timerservice.TimerImpl.assertTimerState(TimerImpl.java:476)
at org.jboss.as.ejb3.timerservice.TimerImpl.isPersistent(TimerImpl.java:226)
at com.sun.ts.tests.ejb30.timer.schedule.lifecycle.ScheduleBean.getTimerHandle(ScheduleBean.java:70)
...
```

**Comment by chengfang** [comment]
Any updates?  These tests, and a few other jakartaee-tck issues filed by me, are causing test failures quite often when running with WildFly.

**Comment by RohitKumarJain** [comment]
@chengfang , I am looking into this issue, please allow me some time to get back to you. Earlier I got engaged with some other task hence couldn't spend much time analyzing this issue.

**Comment by RohitKumarJain** [comment]
@chengfang , looking forward to your inputs. Thanks

**Comment by chengfang** [comment]
@RohitKumarJain this test is time-sensitive and is not always reproducible. But to reproduce it does not require any extra steps; just need to run this test (or the whole test directory, or an entire test area like tests/ejb30/timer), and at certain time, it may fail.

I think we can wrap these timer method invocations with try-catch of `javax.ejb.NoSuchObjectLocalException` and ignore the exception and pass the tests:

```java
    public void timerEquals() {
        ...
        //calling scheduleBean.getTimerHandle(t1) once inside 
        //try catch NoSuchObjectLocalException
        assertNotEquals("Compare timer to TimerHandle.", t1, scheduleBean.getTimerHandle(t1));
        assertNotEquals("Compare TimerHandle to timer.", scheduleBean.getTimerHandle(t1), t1);
       
        assertNotEquals("Compare 2 timers.", t1, t2);
        assertNotEquals("Compare timer 3 to timer 4.", t3, t4);

        // try catch javax.ejb.NoSuchObjectLocalException next line
        scheduleBean.cancelTimer(t1, t2, t3, t4);
    }

```

**Comment by RohitKumarJain** [comment]
@chengfang , are we good to close this issue? As I can see PR is merged.
