### ISSUE TITLE
Second-later calendar-based timer can be too short for some tests

### ISSUE THREAD

**Issue by chengfang** [eclipse-ee4j/jakartaee-tck#136]
Some cts tests create a second-later calendar-based timer, and expect it to fire shortly.  For example, in `com.sun.ts.tests.ejb30.timer.common.TimerBeanBaseWithoutTimeOutMethod` class:

```java
    public Timer createSecondLaterTimer(String name) {
        return TimerUtil.createSecondLaterTimer(timerService, name);
    }

    public Timer createSecondLaterTimer(TimerConfig timerConfig) {
        return TimerUtil.createSecondLaterTimer(timerService, timerConfig);
    }
```

And in `TimerUtil class`:

```java
    public static Timer createSecondLaterTimer(TimerService timerService,
            TimerInfo info) {
        Calendar cal = Calendar.getInstance();
        cal.add(Calendar.SECOND, 1);  //next second
        return timerService.createCalendarTimer(getPreciseScheduleExpression(cal),
                new TimerConfig(info, true));
    }
```

Timers created this way only have precision up to second. If such a `ScheduleExpression` is created towards the end of a second, then the timer is set to expire in just a few milliseconds.  When the ejb container creates the new timer, the `ScheduleExpression` passed to the timer create method may already represent a time in the past.  So the test timer will not fire and the test will not get the expected result.

For example,

calling createSecondLaterTimer(...) at: 11:06:37,990
creating timer to expire at:                     11:06:38,000
ejb container create the timer at:          11:06:38,200

This has occassionally caused test failures when running with WildFly:

11:06:38,936 INFO  [org.jboss.as.ejb3.timer] (default task-1) WFLYEJB0017: Next expiration is null. No tasks will be scheduled for timer [ID=880F2CEC-333D-4D08-B152-376EE69A0428 TIMEDOBJECTID=EJB32_LITE_TIMER_SCHEDULE_TX_EJBLITESERVLET_VEHICLE_WEB.EJB32_LITE_TIMER_SCHEDULE_TX_EJBLITESERVLET_VEHICLE_WEB.SCHEDULEBMTBEAN AUTO-TIMER?:FALSE PERSISTENT?:FALSE TIMERSERVICE=ORG.JBOSS.AS.EJB3.TIMERSERVICE.TIMERSERVICEIMPL@340D51E0 INITIALEXPIRATION=NULL INTERVALDURATION(IN MILLI SEC)=0 NEXTEXPIRATION=NULL TIMERSTATE=ACTIVE INFO=TIMERINFO TESTNAME=TIMEOUTSYSTEMEXCEPTIONBMT TESTNUMBER=0 STATUS=FALSE DOUBLEVAR=0.0 LONGVAR=0 CHARVAR=  BOOLEANVAR=FALSE INTVAR=0] SCHEDULEEXPRESSION [SECOND=38;MINUTE=6;HOUR=11;DAYOFMONTH=13;MONTH=11;DAYOFWEEK=*;YEAR=2019;TIMEZONEID=NULL;START=NULL;END=NULL]

Any tests that use the above testing mechanism suffer from this problem.  We've so far noticed failures in the following tests:

```
com/sun/ts/tests/ejb30/timer/interceptor/aroundtimeout/singleton/annotated/Client.java#aroundTimeoutMethod_from_ejbliteservlet

com/sun/ts/tests/ejb30/timer/interceptor/aroundtimeout/singleton/annotated/Client.java\#aroundTimeoutMethod2_from_ejbliteservlet 

com/sun/ts/tests/ejb30/timer/schedule/txnonpersistent/Client.java\#createRollbackTxPropagationBMT_from_ejbliteservlet

com/sun/ts/tests/ejb30/timer/schedule/descriptor/stateless/Client.java\#programmatic_from_ejbliteservlet 

com/sun/ts/tests/ejb32/lite/timer/schedule/txnonpersistent/Client.java\#createRollbackTxPropagationBMT_from_ejbliteservlet 

com/sun/ts/tests/ejb32/lite/timer/schedule/tx/Client.java\#timeoutSystemExceptionBMT_from_ejbliteservlet

com/sun/ts/tests/ejb32/lite/timer/schedule/tx/Client.java\#timeoutSystemException_from_ejblitejsf 

com/sun/ts/tests/ejb32/lite/timer/schedule/txnonpersistent/Client.java\#timeoutSystemExceptionBMT_from_ejblitejsf 

com/sun/ts/tests/ejb32/lite/timer/schedule/txnonpersistent/Client.java\#timeoutSystemException_from_ejbliteservlet 

com/sun/ts/tests/ejb32/lite/timer/interceptor/aroundtimeout/singleton/annotated/Client.java\#allInterceptorsOverride_from_ejbliteservlet 

com/sun/ts/tests/ejb32/lite/timer/interceptor/aroundtimeout/singleton/annotated/Client.java\#allInterceptorsOverride_from_ejblitejsp 

com/sun/ts/tests/ejb32/lite/timer/schedule/expire/Client.java\#timerAccessInTimeoutMethod_from_ejblitejsf 

com/sun/ts/tests/ejb32/lite/timer/schedule/descriptor/stateless/Client.java\#programmatic_from_ejbliteservlet 
```
The test client side errors may vary, but the root cause is that the test client did not get the expected result because the test timer did not expire.

The test error message for `timeoutSystemExceptionBMT` test:

```
[javatest.batch] INFO: Connecting http://localhost:8080/ejb32_lite_timer_schedule_tx_ejbliteservlet_vehicle_web/ejbliteservlet_vehicle.jsp?testName=timeoutSystemExceptionBMT
[javatest.batch] [TEST FAILED] testName=timeoutSystemExceptionBMT If the transaction rolls back in timeout method, must retry at least once.
[javatest.batch] timeout callback result: 
[javatest.batch] []
[javatest.batch] 
[javatest.batch] Expecting 0>1, but failedFailed with exception 
[javatest.batch] java.lang.RuntimeException: If the transaction rolls back in timeout method, must retry at least once.
[javatest.batch] timeout callback result: 
[javatest.batch] []
[javatest.batch] 
[javatest.batch] Expecting 0>1, but failed
[javatest.batch] 	at com.sun.ts.tests.ejb30.common.helper.Helper.assertGreaterThan(Helper.java:155)
[javatest.batch] 	at com.sun.ts.tests.ejb30.common.lite.EJBLiteClientBase.assertGreaterThan(EJBLiteClientBase.java:394)
[javatest.batch] 	at com.sun.ts.tests.ejb32.lite.timer.schedule.tx.ClientBase.timeoutRollback(ClientBase.java:239)
[javatest.batch] 	at com.sun.ts.tests.ejb32.lite.timer.schedule.tx.ClientBase.timeoutSystemExceptionBMT(ClientBase.java:192)

```

The test error message for `createRollbackTxPropagationBMT` test:

```
[javatest.batch] INFO: Connecting http://localhost:8080/ejb30_timer_schedule_txnonpersistent_ejbliteservlet_vehicle_web/ejbliteservlet_vehicle.jsp?testName=createRollbackTxPropagationBMT
[javatest.batch] [TEST FAILED] testName=createRollbackTxPropagationBMT []
[javatest.batch] 
[javatest.batch] 
[javatest.batch] Check timeout status Expecting true, but actual nullFailed with exception 
[javatest.batch] java.lang.RuntimeException: []
[javatest.batch] 
[javatest.batch] 
[javatest.batch] Check timeout status Expecting true, but actual null
[javatest.batch] 	at com.sun.ts.tests.ejb30.common.helper.Helper.assertEquals(Helper.java:89)
[javatest.batch] 	at com.sun.ts.tests.ejb30.common.lite.EJBLiteClientBase.assertEquals(EJBLiteClientBase.java:384)
[javatest.batch] 	at com.sun.ts.tests.ejb30.timer.common.ClientBase.passIfTimeout(ClientBase.java:91)
[javatest.batch] 	at com.sun.ts.tests.ejb30.timer.common.ClientBase.passIfTimeout(ClientBase.java:79)
[javatest.batch] 	at com.sun.ts.tests.ejb30.timer.schedule.tx.ClientBase.createRollbackTxPropagationBMT(ClientBase.java:101)

```

The test error for `allInterceptorsOverride` test:

```
Feb 05, 2020 12:38:33 AM com.sun.ts.tests.common.vehicle.ejbliteshare.EJBLiteWebVehicleRunner run
INFO: Connecting http://localhost:8080/ejb32_lite_timer_interceptor_aroundtimeout_singleton_annotated_ejbliteservlet_vehicle_web/ejbliteservlet_vehicle.jsp?testName=allInterceptorsOverride
[TEST FAILED] testName=allInterceptorsOverride []


Check timeout status Expecting true, but actual nullFailed with exception 
java.lang.RuntimeException: []


Check timeout status Expecting true, but actual null
	at com.sun.ts.tests.ejb30.common.helper.Helper.assertEquals(Helper.java:72)
	at com.sun.ts.tests.ejb30.common.lite.EJBLiteClientBase.assertEquals(EJBLiteClientBase.java:355)
	at com.sun.ts.tests.ejb30.timer.common.ClientBase.passIfTimeout(ClientBase.java:73)
	at com.sun.ts.tests.ejb30.timer.common.ClientBase.passIfTimeout(ClientBase.java:61)
	at com.sun.ts.tests.ejb30.timer.interceptor.aroundtimeout.common.ClientBase.checkAndClearAroundTimeoutRecords(ClientBase.java:186)
	at com.sun.ts.tests.ejb30.timer.interceptor.aroundtimeout.common.ClientBase.aroundTimeoutTest(ClientBase.java:180)
	at com.sun.ts.tests.ejb30.timer.interceptor.aroundtimeout.common.ClientBase.allInterceptorsOverride(ClientBase.java:80)
```

These tests need to be improved to have longer delay, or make it configurable.

**Comment by chengfang** [comment]
We are seeing more of these failures when running with WildFly.  So I tried a fix in the above PR. Basically changing 1-second-later timers to 2-second-later timers for those tests affected by this issue.

**Comment by chengfang** [comment]
Added the following 2 tests to the list of failures in the issue description section:

```
com/sun/ts/tests/ejb30/timer/interceptor/aroundtimeout/singleton/annotated/Client.java\#aroundTimeoutMethod2_from_ejbliteservlet 

com/sun/ts/tests/ejb32/lite/timer/schedule/expire/Client.java\#timerAccessInTimeoutMethod_from_ejblitejsf

```

**Comment by chengfang** [comment]
Added the following test to the list of failures in the issue description section:

```
 com/sun/ts/tests/ejb32/lite/timer/schedule/descriptor/stateless/Client.java\#programmatic_from_ejbliteservlet 
```

I'll update the PR to include fix for this test directory as well.

**Comment by scottmarlow** [comment]
Thanks @chengfang for the fix!
