### ISSUE TITLE
Javamail CTS tests fails due to mail server start up issue in Eclipse CJE infrastructure

### ISSUE THREAD

**Issue by anajosep** [eclipse-ee4j/jakartaee-tck#22]
Javamail server is started as part of the pod instance used for testing. However, when the javamail server is used by testing, Authentication exception is being thrown.
The issue does not happen always. If Javmail test suite alone is re-run, it passes. So this might be infrastructure related as well.

javax.mail.AuthenticationFailedException: AUTHENTICATE failed. Authentication failed.
	at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:708)
	at javax.mail.Service.connect(Service.java:364)
	at com.sun.ts.tests.javamail.ee.common.MailTestUtil.connect2host(MailTestUtil.java:319)
	at com.sun.ts.tests.javamail.ee.fetchprofile.fetchprofile_Test.setup(fetchprofile_Test.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ts.lib.harness.EETest.run(EETest.java:569)
	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:115)
	at com.sun.ts.tests.common.vehicle.EmptyVehicleRunner.run(EmptyVehicleRunner.java:40)
	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:105)
	at com.sun.ts.lib.harness.EETest.getPropsReady(EETest.java:486)
	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:209)
	at com.sun.ts.lib.harness.EETest.run(EETest.java:285)
	at com.sun.ts.tests.common.vehicle.VehicleClient.main(VehicleClient.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.appclient.client.acc.AppClientContainer.launch(AppClientContainer.java:422)
	at org.glassfish.appclient.client.AppClientFacade.launch(AppClientFacade.java:159)
	at org.glassfish.appclient.client.AppClientGroupFacade.main(AppClientGroupFacade.java:41)
java.lang.IllegalStateException: Not connected
	at com.sun.mail.imap.IMAPStore.checkConnected(IMAPStore.java:1959)
	at com.sun.mail.imap.IMAPStore.getDefaultFolder(IMAPStore.java:1726)
	at com.sun.ts.tests.javamail.ee.fetchprofile.fetchprofile_Test.getRootFolder(fetchprofile_Test.java:328)
	at com.sun.ts.tests.javamail.ee.fetchprofile.fetchprofile_Test.setup(fetchprofile_Test.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ts.lib.harness.EETest.run(EETest.java:569)
	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:115)
	at com.sun.ts.tests.common.vehicle.EmptyVehicleRunner.run(EmptyVehicleRunner.java:40)
	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:105)
	at com.sun.ts.lib.harness.EETest.getPropsReady(EETest.java:486)
	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:209)
	at com.sun.ts.lib.harness.EETest.run(EETest.java:285)
	at com.sun.ts.tests.common.vehicle.VehicleClient.main(VehicleClient.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.appclient.client.acc.AppClientContainer.launch(AppClientContainer.java:422)
	at org.glassfish.appclient.client.AppClientFacade.launch(AppClientFacade.java:159)
	at org.glassfish.appclient.client.AppClientGroupFacade.main(AppClientGroupFacade.java:41)
01-05-2019 10:48:29:  ERROR: Exception : null
01-05-2019 10:48:29:  ERROR: Setup Failed!
01-05-2019 10:48:29:  ERROR: java.lang.NullPointerException
	at com.sun.ts.tests.javamail.ee.fetchprofile.fetchprofile_Test.setup(fetchprofile_Test.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ts.lib.harness.EETest.run(EETest.java:569)
	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:115)
	at com.sun.ts.tests.common.vehicle.EmptyVehicleRunner.run(EmptyVehicleRunner.java:40)
	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:105)
	at com.sun.ts.lib.harness.EETest.getPropsReady(EETest.java:486)
	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:209)
	at com.sun.ts.lib.harness.EETest.run(EETest.java:285)
	at com.sun.ts.tests.common.vehicle.VehicleClient.main(VehicleClient.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.appclient.client.acc.AppClientContainer.launch(AppClientContainer.java:422)
	at org.glassfish.appclient.client.AppClientFacade.launch(AppClientFacade.java:159)
	at org.glassfish.appclient.client.AppClientGroupFacade.main(AppClientGroupFacade.java:41)

01-05-2019 10:48:29:  ERROR: Unexpected Exception null
01-05-2019 10:48:29:  ERROR: java.lang.NullPointerException
	at com.sun.ts.tests.javamail.ee.fetchprofile.fetchprofile_Test.test2(fetchprofile_Test.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ts.lib.harness.EETest.run(EETest.java:596)
	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:115)
	at com.sun.ts.tests.common.vehicle.EmptyVehicleRunner.run(EmptyVehicleRunner.java:40)
	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:105)
	at com.sun.ts.lib.harness.EETest.getPropsReady(EETest.java:486)
	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:209)
	at com.sun.ts.lib.harness.EETest.run(EETest.java:285)
	at com.sun.ts.tests.common.vehicle.VehicleClient.main(VehicleClient.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.appclient.client.acc.AppClientContainer.launch(AppClientContainer.java:422)
	at org.glassfish.appclient.client.AppClientFacade.launch(AppClientFacade.java:159)
	at org.glassfish.appclient.client.AppClientGroupFacade.main(AppClientGroupFacade.java:41)

01-05-2019 10:48:29:  ERROR: test2 Failed
01-05-2019 10:48:29:  ERROR: Test case throws exception: test2 Failed
01-05-2019 10:48:29:  ERROR: Exception at:  
01-05-2019 10:48:29:  ERROR: com.sun.ts.lib.harness.EETest$Fault: test2 Failed
	at com.sun.ts.tests.javamail.ee.fetchprofile.fetchprofile_Test.test2(fetchprofile_Test.java:242)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ts.lib.harness.EETest.run(EETest.java:596)
	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:115)
	at com.sun.ts.tests.common.vehicle.EmptyVehicleRunner.run(EmptyVehicleRunner.java:40)
	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:105)
	at com.sun.ts.lib.harness.EETest.getPropsReady(EETest.java:486)
	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:209)
	at com.sun.ts.lib.harness.EETest.run(EETest.java:285)
	at com.sun.ts.tests.common.vehicle.VehicleClient.main(VehicleClient.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.appclient.client.acc.AppClientContainer.launch(AppClientContainer.java:422)
	at org.glassfish.appclient.client.AppClientFacade.launch(AppClientFacade.java:159)
	at org.glassfish.appclient.client.AppClientGroupFacade.main(AppClientGroupFacade.java:41)

**Comment by bhatpmk** [comment]
The standard output from Apache James mail server is requested using https://bugs.eclipse.org/bugs/show_bug.cgi?id=543508. As mentioned in the description, the issue happens intermittently, the tests passed in [run#29](https://jenkins.eclipse.org/jakartaee-tck/job/jakartaeetck-nightly-run/29/junit-reports-with-handlebars/testSuitesOverview.html)
