### ISSUE TITLE
Intermittent failure for jaxrs test sseStageCheckTest_from_standalone 

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/jakartaee-tck#25]
The jaxrs test sseStageCheckTest_from_standalone fails intermittently. The issue need to be analysed further.

> 01-07-2019 22:22:38:  ERROR: InboundEvent{name='null', id='null', comment=[no comments], data=CompletionStage has been done} does not contain expected some_ServiceUnavailableEndpoint_message
> 01-07-2019 22:22:38:  ERROR: Test case throws exception: InboundEvent{name='null', id='null', comment=[no comments], data=CompletionStage has been done} does not contain expected some_ServiceUnavailableEndpoint_message
> 01-07-2019 22:22:38:  ERROR: Exception at:  
> 01-07-2019 22:22:38:  ERROR: com.sun.ts.lib.harness.EETest$Fault: InboundEvent{name='null', id='null', comment=[no comments], data=CompletionStage has been done} does not contain expected some_ServiceUnavailableEndpoint_message
> 	at com.sun.ts.tests.jaxrs.common.JAXRSCommonClient.fault(JAXRSCommonClient.java:767)
> 	at com.sun.ts.tests.jaxrs.common.JAXRSCommonClient.assertTrue(JAXRSCommonClient.java:662)
> 	at com.sun.ts.tests.jaxrs.jaxrs21.ee.sse.sseeventsink.JAXRSClient.sseStageCheckTest(JAXRSClient.java:318)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.sun.ts.lib.harness.EETest.run(EETest.java:596)
> 	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:115)
> 	at com.sun.ts.tests.common.vehicle.EmptyVehicleRunner.run(EmptyVehicleRunner.java:40)
> 	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:105)
> 	at com.sun.ts.lib.harness.EETest.getPropsReady(EETest.java:486)
> 	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:209)
> 	at com.sun.ts.lib.harness.EETest.run(EETest.java:285)
> 	at com.sun.ts.tests.common.vehicle.VehicleClient.main(VehicleClient.java:38)
> 
> 01-07-2019 22:22:38:  [JAXRSCommonClient] Test cleanup OK
> STATUS:Failed.Test case throws exception: InboundEvent{name='null', id='null', comment=[no comments], data=CompletionStage has been done} does not contain expected some_ServiceUnavailableEndpoint_message
> result: Failed. Test case throws exception: InboundEvent{name='null', id='null', comment=[no comments], data=CompletionStage has been done} does not contain expected some_ServiceUnavailableEndpoint_message
> 
> 
> test result: Failed. Test case throws exception: InboundEvent{name='null', id='null', comment=[no comments], data=CompletionStage has been done} does not contain expected some_ServiceUnavailableEndpoint_message

**Comment by alwin-joseph** [comment]
This test has been passing consistently for several runs. The issue has not occurred for a long time.
Recent test result junit report for jaxrs : https://ci.eclipse.org/jakartaee-tck/job/standalonetck-nightly-build-run/138/junit-reports-with-handlebars/test-summary/3d84f6b4-148b-429b-8f77-0c95add5aeb9.html
