### ISSUE TITLE
new batch test failures

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-tck#410]
https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/891/testReport/com.ibm.jbatch.tck.tests.jslxml/ContextAndListenerTests/jakartaeetck_run___jbatch___testgetExceptionListenerBased_from_web/ is one of multiple Batch test failures from [this weeks GlassFish 6.0 weekly build](https://download.eclipse.org/ee4j/glassfish/weekly/glassfish-6.0.0-SNAPSHOT-2020-08-02.zip).

@scottkurz are more jakartaee-tck test changes needed for Jakarta Batch that might help with these failures?  Do we need a jakartaee-tck change similar to https://github.com/eclipse-ee4j/batch-tck/commit/3cc0dd2408a6fde19340d8c344c1f157bdcd615d?

@smillidge do you know if any more GlassFish 6.0 changed needed for Jakarta Batch support?

Exception from the above test link:
```
SVR-ERROR: jakarta.batch.operations.JobStartException: java.lang.NullPointerException
	at com.ibm.jbatch.container.api.impl.JobOperatorImpl.start(JobOperatorImpl.java:92)
	at com.ibm.jbatch.tck.utils.JobOperatorBridge.startJobAndWaitForResult(JobOperatorBridge.java:148)
	at com.ibm.jbatch.tck.tests.jslxml.ContextAndListenerTests.testgetExceptionListenerBased(ContextAndListenerTests.java:239)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ts.lib.harness.EETest.run(EETest.java:596)
	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:115)
	at com.sun.ts.tests.common.vehicle.servlet.ServletVehicle.runTest(ServletVehicle.java:116)
	at com.sun.ts.tests.common.vehicle.servlet.ServletVehicle.doGet(ServletVehicle.java:88)
	at com.sun.ts.tests.common.vehicle.servlet.ServletVehicle.doPost(ServletVehicle.java:108)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:520)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
	at sun.reflect.GeneratedMethodAccessor152.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:275)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:273)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:308)
	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:166)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1534)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:119)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:611)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:550)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:75)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:114)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:332)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:199)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:440)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:144)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:174)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:153)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:196)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:248)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:181)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:121)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:99)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:34)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at javax.xml.validation.SchemaFactory.newSchema(SchemaFactory.java:670)
	at com.ibm.jbatch.jsl.util.ValidatorHelper.getXJCLSchema(ValidatorHelper.java:44)
	at com.ibm.jbatch.container.jsl.impl.JobModelResolverImpl.unmarshalJobXML(JobModelResolverImpl.java:58)
	at com.ibm.jbatch.container.jsl.impl.JobModelResolverImpl.access$000(JobModelResolverImpl.java:45)
	at com.ibm.jbatch.container.jsl.impl.JobModelResolverImpl$1.run(JobModelResolverImpl.java:127)
	at com.ibm.jbatch.container.jsl.impl.JobModelResolverImpl$1.run(JobModelResolverImpl.java:125)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.ibm.jbatch.container.jsl.impl.JobModelResolverImpl.resolveModel(JobModelResolverImpl.java:123)
	at com.ibm.jbatch.container.jsl.impl.JobModelResolverImpl.resolveModel(JobModelResolverImpl.java:45)
	at com.ibm.jbatch.container.jobinstance.JobExecutionHelper.startJob(JobExecutionHelper.java:114)
	at com.ibm.jbatch.container.impl.BatchKernelImpl.startJob(BatchKernelImpl.java:124)
	at com.ibm.jbatch.container.api.impl.JobOperatorImpl.startInternal(JobOperatorImpl.java:123)
	at com.ibm.jbatch.container.api.impl.JobOperatorImpl.start(JobOperatorImpl.java:88)
	... 50 more
```

**Comment by smillidge** [comment]
@scottmarlow JBatch integration into GlassFish is a very thin wrapper on the RI. I can check to see if it is all done afaik and check back. There may have been new component versions released that are not integrated.

**Comment by scottmarlow** [comment]
@smillidge thanks, I did notice recent https://github.com/eclipse-ee4j/batch-api/pull/103 which incremented the JBatch schema to 2.0.  Perhaps that is a change not yet integrated (just a guess on my part).

**Comment by smillidge** [comment]
@scottkurz did integrate that version here https://github.com/eclipse-ee4j/glassfish/pull/23126 however I will check whether the correct schema is also packaged with the server.

**Comment by smillidge** [comment]
I can't see that the schema was previously packaged by the server so I assume it comes in the api or impl jar.

**Comment by smillidge** [comment]
Looking at https://github.com/WASdev/standards.jsr352.jbatch/blob/master/com.ibm.jbatch.container/src/main/java/com/ibm/jbatch/jsl/util/ValidatorHelper.java#L43 looks like it is failing to load the schema resource. It is in the api jar at the path specified. As this code is in the container jar my gut feeling is OSGI classloading is the problem. @scottkurz did you change anything around OSGI imports/exports. 

I will have a play outside of the TCK to see if there is a general issue deploying a batch test app.

**Comment by smillidge** [comment]
Apologies for the running commentary but I just checked GlassFish 5 and the xsd was packaged in the RI container jar and NOT in the api jar. In the version now packaged in GlassFish 6 the xsd is in the api jar and NOT the container jar.

I think this is causing classloader issues under OSGI. So I think this is back to @scottkurz to see if he is packaging the various jars differently.

**Comment by scottkurz** [comment]
There was a change here, which I hadn't thought to mention but, looking back should have.   

Previously we'd packaged the XSD file within the jbatch impl JAR.   Along with making the last 2.0 schema changes we also started packaging the XSD within the API jar, for the first time, and at the same time I pulled it out of the jbatch impl JAR.

The XSD is located at path: 
`xsd/jobXML_2_0.xsd`

Does anyone know off the top of their head how to export/import this resource in OSGi?

**Comment by smillidge** [comment]
I think you have to export and import xsd respectively or use the OSGI Bundle api. 
Alternatively use the classloader for an api class?

**Comment by scottkurz** [comment]
After reading a bit, I think exporting/importing the xsd "package" seems a bit of a hack.  We'd at least probably want a more jakarta-specific qualifier, but I like the idea of instead fixing 'jbatch' to use the OSGi Bundle API like Steve suggested.  

An added bonus of this decision would be that the API JAR itself doesn't needed to be re-spun (it is already staged for the 2.0.0 release)... not that we couldn't still if that were the right thing to do, but just noting.

I don't mind doing the fix in jbatch but I have to be able to run locally.. it'll be too slow to continually do jbatch release, test in GF, etc.

One thing holding me back:   I downloaded the **glassfish-6.0.0-SNAPSHOT-2020-08-02.zip** linked above and I can't get any Batch servlet to even run, not the glassfish-samples javax->jakarta-ized, not my own samples.    I keep getting all kinds of 404 errors.

I don't want to have to run the TCK, I'm not familiar with that automation.

@smillidge @OndroMih -    are there any instructions for running a simple Batch Hello World or other EE 9-level sample on Glassfish?     I understand the JavaDB part is pre-configured by default.. (there isn't something I need to set up there right?).

Open Liberty uses OSGi so that's an option too but I was hoping Glassfish would be quicker.  

Thanks, and again, sorry for not thinking of this before...  it seems obvious in retrospect.  It did pop into my head and one point but it faded too quickly.

**Comment by scottmarlow** [comment]
Some instructions for running Platform TCK tests in general are shown at https://github.com/eclipse-ee4j/jakartaee-tck/wiki/Instructions-for-running-the-nightly-engineering-build-of-Platform-TCK-with-Podman-(currently-for-EE-9)

I will try ^ with ```bash -x jakartaeetck/docker/run_jakartaeetck.sh batch 2>&1 | tee run_cts.log```

**Comment by smillidge** [comment]
As Batch uses the database you will likely have to run `asadmin start-database` before you run `asadmin start-domain` if you want to point me to your test app I can take a look.

**Comment by scottkurz** [comment]
@smillidge thx for offering to help.  

Is the `start-database` just starting the "Network Server" (vs. embedded) database?  In any case I don't think that was the issue.   I got past my basic webcontainer issues just by blowing away the install :).    

I have coded up something which seems to "work": https://github.com/WASdev/standards.jsr352.jbatch/commits/66-osgi-xsd-load

However there's an issue, which is that I can only access BundleContext like I'm trying to do if I go into the osgi-shell and manually start the com.ibm.jbatch.container bundle.

Is there a setting I should be doing to auto-start this?    I'm running code in this bundle, how is it not started?   I'm just unzipping the GF install, then doing:  `asadmin start-domain` then `asadmin deploy --force my.war`.

Even if there is, I'm worried that the fact I'd have to do this implies it wouldn't work by default, out of the box for most users.     

At this point I probably should just zip up the XSD file in the jbatch JAR and abandon this idea.    

Still, let me hear what you think.  If we're close then, well, I already have this coded up.    I could write up recreate instructions too.. basically it's:

1. build the jbatch stuff with `-Pstaging`   
2. mvn package the WAR at:  https://github.com/WASdev/sample.batch.sleepybatchlet/tree/jakarta9
3.  deploy 
4. URL:   http://localhost:8080/SleepyBatchletSample-1.0/joboperator?action=start&jobXMLName=sleepy-batchlet

(But like I said I had to start the bundle manually..it was just INSTALLED).

Thanks.

**Comment by scottkurz** [comment]
@smillidge ..nevermind, there's no value in pursuing the OSGi loading.. I'm just going to ship a 2.0.0-M7 with the XSD zipped up.. In the process of testing it now.. should be available in the next couple of days.

**Comment by smillidge** [comment]
alternative is to load the resource via an api classloader using an api class rather than a container class. Otherwise just duplicate the xsd in the container jar in the same location.

**Comment by scottkurz** [comment]
Fix PR in:  https://github.com/eclipse-ee4j/glassfish/pull/23157/  pulling in 2.0.0-M7

**Comment by scottmarlow** [comment]
Thanks @scottkurz + @smillidge, The Full Platform TCK run https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/911/testReport/ is passing the JBatch tests with https://download.eclipse.org/ee4j/glassfish/weekly/glassfish-6.0.0-SNAPSHOT-2020-08-09.zip!
