### ISSUE TITLE
Separate tests that use XML binding (e.g. xml_binding) in com/sun/ts/tests/jaxrs/spec/provider/standard, com/sun/ts/tests/jaxrs/spec/client/typedentities

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-tck#518]
Update keyword.properties to reflect that XML binding (xml_binding) tests were moved from com/sun/ts/tests/jaxrs/spec/provider/standard, com/sun/ts/tests/jaxrs/spec/client/typedentities to a new test subfolder.

**Comment by scottmarlow** [comment]
Down to only one failure, so almost done:
```
[javatest.batch] 09-23-2020 15:15:20:  [HttpRequest] Dispatching request: 'POST /jaxrs_spec_provider_standardwithxmlbinding_web/resource/jaxb HTTP/1.1' to target server at 'localhost:8080'
[javatest.batch] 09-23-2020 15:15:20:  ERROR: [WebValidatorBase] Unexpected Status Code recieved from server.  Expected '200' received '404'
[javatest.batch] 09-23-2020 15:15:20:  ERROR: Test case throws exception: [JAXRSCommonClient] null failed! Check output for cause of failure.
[javatest.batch] 09-23-2020 15:15:20:  ERROR: Exception at:
[javatest.batch] 09-23-2020 15:15:20:  ERROR: com.sun.ts.tests.common.webclient.TestFailureException: Test FAILED!
[javatest.batch]        at com.sun.ts.tests.common.webclient.WebTestCase.execute(WebTestCase.java:180)
[javatest.batch]        at com.sun.ts.tests.jaxrs.common.JAXRSCommonClient.invoke(JAXRSCommonClient.java:307)
[javatest.batch]        at com.sun.ts.tests.jaxrs.spec.provider.standardwithxmlbinding.JAXRSClient.setPropertyAndInvoke(JAXRSClient.java:44)
[javatest.batch]        at com.sun.ts.tests.jaxrs.spec.provider.standardwithxmlbinding.JAXRSClient.setPropertyAndInvokeXml(JAXRSClient.java:51)
[javatest.batch]        at com.sun.ts.tests.jaxrs.spec.provider.standardwithxmlbinding.JAXRSClient.setPropertyAndInvokeXml(JAXRSClient.java:55)
[javatest.batch]        at com.sun.ts.tests.jaxrs.spec.provider.standardwithxmlbinding.JAXRSClient.jaxbElementProviderTest(JAXRSClient.java:93)
[javatest.batch]        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[javatest.batch]        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[javatest.batch]        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[javatest.batch]        at java.lang.reflect.Method.invoke(Method.java:498)
[javatest.batch]        at com.sun.ts.lib.harness.EETest.run(EETest.java:596)
[javatest.batch]        at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:115)
[javatest.batch]        at com.sun.ts.tests.common.vehicle.EmptyVehicleRunner.run(EmptyVehicleRunner.java:40)
[javatest.batch]        at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:105)
[javatest.batch]        at com.sun.ts.lib.harness.EETest.getPropsReady(EETest.java:486)
[javatest.batch]        at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:209)
[javatest.batch]        at com.sun.ts.lib.harness.EETest.run(EETest.java:285)
[javatest.batch]        at com.sun.ts.tests.common.vehicle.VehicleClient.main(VehicleClient.java:38)
[javatest.batch]
[javatest.batch] 09-23-2020 15:15:20:  [JAXRSCommonClient] Test cleanup OK
[javatest.batch] STATUS:Failed.Test case throws exception: [JAXRSCommonClient] null failed! Check output for cause of failure.
[javatest.batch] Sep 23, 2020 3:15:21 PM Finished executing all tests, wait for cleanup...
[javatest.batch] Sep 23, 2020 3:15:21 PM Harness done with cleanup from test run.
[javatest.batch] Failed. Test case throws exception: [JAXRSCommonClient] null failed! Check output for cause of failure.
```
