### ISSUE TITLE
ClassNotFoundException: webservices12/ejb/annotations/WSEjbWebServiceRefWithNoDDsTest/Client

### ISSUE THREAD

**Issue by hussainnm** [eclipse-ee4j/jakartaee-tck#668]
Two tests are failing because of the `ClassNotFoundException`.

```
Error: Could not find or load main class com.sun.ts.tests.webservices12.ejb.annotations.WSEjbWebServiceRefWithNoDDsTest.Client
Caused by: java.lang.ClassNotFoundException: com.sun.ts.tests.webservices12.ejb.annotations.WSEjbWebServiceRefWithNoDDsTest.Client
result: Failed. unexpected exit code: exit code 1
```

https://ci.eclipse.org/jakartaee-tck/job/9.1/job/eftl-jakartaeetck-run-910/30/testReport/com.sun.ts.tests.webservices12.ejb.annotations.WSEjbWebServiceRefWithNoDDsTest/Client/WSEjbWebServiceRefWithNoDDsTestCallHello/

https://ci.eclipse.org/jakartaee-tck/job/9.1/job/eftl-jakartaeetck-run-910/30/testReport/com.sun.ts.tests.webservices12.ejb.annotations.WSEjbWebServiceRefWithNoDDsTest/Client/WSEjbWebServiceRefWithNoDDsTestCallBye/

The `Client.java` is not being built for this package.

**Comment by hussainnm** [comment]
This seems to have been fixed. Closing issue.

**Comment by hussainnm** [comment]
Re-opening. Same issue occurred in latest Platform run.

https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1329/testReport/com.sun.ts.tests.webservices12.ejb.annotations.WSEjbWebServiceRefWithNoDDsTest/Client/jakartaeetck_run___webservices12___WSEjbWebServiceRefWithNoDDsTestCallBye/

**Comment by hussainnm** [comment]
I think the root cause could be the below wsgen failure:

```
   [runcts] Building webservices clients ...
   [runcts] Running ==> "/usr/share/ant/bin/ant build.special.webservices.clients"
   [runcts] OUT => Buildfile: /root/jakartaeetck/bin/build.xml
   [runcts] OUT =>      [echo] ts.home = /root/jakartaeetck/bin/xml/../..
   [runcts] OUT =>      [echo] In a bundle
   [runcts] OUT =>      [echo] The deliverable currently in use is /root/jakartaeetck/bin/xml/../../bin.
   [runcts] OUT => Trying to override old definition of datatype string
   [runcts] OUT => 
   [runcts] OUT => build.special.webservices.clients:
   [runcts] OUT =>      [echo] ts.home = /root/jakartaeetck/bin/xml/../..
   [runcts] OUT =>      [echo] In a bundle
   [runcts] OUT =>      [echo] The deliverable currently in use is /root/jakartaeetck/bin/xml/../../bin.
   [runcts] OUT => 
   [runcts] OUT => build.specialcases.clients:
   [runcts] OUT => [dosubdirs] Entering /root/jakartaeetck/bin/xml/../../src/com/sun/ts/tests/webservices12/ejb/annotations/WSEjbWebServiceRefWithNoDDsTest
   [runcts] OUT =>      [echo] ts.home = /root/jakartaeetck/bin/xml/../..
   [runcts] OUT =>      [echo] In a bundle
   [runcts] OUT =>      [echo] The deliverable currently in use is /root/jakartaeetck/bin/xml/../../bin.
   [runcts] OUT => 
   [runcts] OUT => clean:
   [runcts] OUT => [dosubdirs] Entering /root/jakartaeetck/bin/xml/../../src/com/sun/ts/tests/webservices12/ejb/annotations/WSEjbWebServiceRefWithNoDDsTest
   [runcts] OUT =>      [echo] ts.home = /root/jakartaeetck/bin/xml/../..
   [runcts] OUT =>      [echo] In a bundle
   [runcts] OUT =>      [echo] The deliverable currently in use is /root/jakartaeetck/bin/xml/../../bin.
   [runcts] OUT => 
   [runcts] OUT => generate_server:
   [runcts] OUT =>  [ts.javac] Compiling 1 source file to /root/jakartaeetck/classes
   [runcts] OUT =>      [echo] ts.home = /root/jakartaeetck/bin/xml/../..
   [runcts] OUT =>      [echo] In a bundle
   [runcts] OUT =>      [echo] The deliverable currently in use is /root/jakartaeetck/bin/xml/../../bin.
   [runcts] OUT => 
   [runcts] OUT => do_java2wsdl_generate_server:
   [runcts] OUT =>     [mkdir] Created dir: /root/jakartaeetck/classes/com/sun/ts/tests/webservices12/ejb/annotations/WSEjbWebServiceRefWithNoDDsTest/generated_classes
   [runcts] OUT =>     [mkdir] Created dir: /root/jakartaeetck/classes/com/sun/ts/tests/webservices12/ejb/annotations/WSEjbWebServiceRefWithNoDDsTest/generated_sources
   [runcts] OUT =>      [echo] wsdlFile=/root/jakartaeetck/bin/xml/../../src/com/sun/ts/tests/webservices12/ejb/annotations/WSEjbWebServiceRefWithNoDDsTest/WSEjbWSRefWithNoDDsTestHelloEJBService.wsdl
   [runcts] OUT =>      [echo] impl=com.sun.ts.tests.webservices12.ejb.annotations.WSEjbWebServiceRefWithNoDDsTest.WSEjbWSRefWithNoDDsTestHelloEJB
   [runcts] OUT =>      [echo] _impl=com/sun/ts/tests/webservices12/ejb/annotations/WSEjbWebServiceRefWithNoDDsTest/WSEjbWSRefWithNoDDsTestHelloEJB
   [runcts] OUT =>      [echo] _impl2=/root/jakartaeetck/bin/xml/../../classes/com/sun/ts/tests/webservices12/ejb/annotations/WSEjbWebServiceRefWithNoDDsTest/WSEjbWSRefWithNoDDsTestHelloEJB.class
   [runcts] OUT =>      [echo] build.vi=false
   [runcts] OUT =>      [echo] ----------------------------------------------------------
   [runcts] OUT =>      [echo] Doing Java-to-WSDL generation using the SUN specific tools
   [runcts] OUT =>      [echo] ----------------------------------------------------------
   [runcts] OUT =>     [wsgen] JAX-WS RI ${project.version}
   [runcts] OUT =>     [wsgen] command line: wsgen-d /root/jakartaeetck/classes/com/sun/ts/tests/webservices12/ejb/annotations/WSEjbWebServiceRefWithNoDDsTest/generated_classes -keep -s /root/jakartaeetck/classes/com/sun/ts/tests/webservices12/ejb/annotations/WSEjbWebServiceRefWithNoDDsTest/generated_sources -verbose -classpath /root/vi/glassfish6/glassfish/modules/jakarta.jms-api.jar:/root/vi/glassfish6/glassfish/modules/jakarta.json.jar:/root/vi/glassfish6/glassfish/modules/jakarta.json.bind-api.jar:/root/vi/glassfish6/glassfish/modules/jakarta.ejb-api.jar:/root/vi/glassfish6/glassfish/modules/jakarta.annotation-api.jar:/root/vi/glassfish6/glassfish/modules/jakarta.enterprise.deploy-api.jar:/root/vi/glassfish6/glassfish/modules/jakarta.mail.jar:/root/vi/glassfish6/glassfish/modules/jakarta.persistence.jar:/root/vi/glassfish6/glassfish/modules/jakarta.resource-api.jar:/root/vi/glassfish6/glassfish/modules/jakarta.security.auth.message-api.jar:/root/vi/glassfish6/glassfish/modules/jakarta.security.jacc-api.jar:/root/vi/glassfish6/glassfish/modules/jakarta.servlet-api.jar:/root/vi/glassfish6/glassfish/modules/el-impl.jar:/root/vi/glassfish6/glassfish/modules/jakarta.servlet.jsp-api.jar:/root/vi/glassfish6/glassfish/modules/jakarta.transaction-api.jar:/root/vi/glassfish6/glassfish/modules/jakarta.xml.bind-api.jar:/root/vi/glassfish6/glassfish/modules/jaxb-osgi.jar:/root/vi/glassfish6/glassfish/modules/jmxremote_optional-repackaged.jar:/root/vi/glassfish6/glassfish/modules/jakarta.faces.jar:/root/vi/glassfish6/glassfish/modules/jakarta.servlet.jsp.jstl.jar:/root/ri/glassfish6/glassfish/modules/jakarta.servlet.jsp.jstl-api.jar:/root/vi/glassfish6/glassfish/modules/webservices-osgi.jar:/root/vi/glassfish6/glassfish/modules/webservices-api-osgi.jar:/root/vi/glassfish6/glassfish/modules/jakarta.management.j2ee-api.jar:/root/vi/glassfish6/glassfish/modules/ejb.security.jar:/root/vi/glassfish6/glassfish/modules/glassfish-corba-csiv2-idl.jar:/root/vi/glassfish6/glassfish/modules/weld-osgi-bundle.jar:/root/vi/glassfish6/glassfish/modules/deployment-client.jar:/root/vi/glassfish6/glassfish/modules/security.jar:/root/vi/glassfish6/glassfish/modules/common-util.jar:/root/vi/glassfish6/glassfish/modules/glassfish-corba-omgapi.jar:/root/vi/glassfish6/glassfish/modules/deployment-common.jar:/root/vi/glassfish6/glassfish/modules/gmbal.jar:/root/vi/glassfish6/glassfish/modules/bean-validator.jar:/root/vi/glassfish6/glassfish/modules/jakarta.ws.rs-api.jar:/root/vi/glassfish6/glassfish/modules/jersey-client.jar:/root/vi/glassfish6/glassfish/modules/jersey-common.jar:/root/vi/glassfish6/glassfish/modules/jersey-hk2.jar:/root/vi/glassfish6/glassfish/modules/jersey-media-jaxb.jar:/root/vi/glassfish6/glassfish/modules/jersey-media-sse.jar:/root/vi/glassfish6/glassfish/modules/jersey-media-json-processing.jar:/root/vi/glassfish6/glassfish/modules/jsonp-jaxrs.jar:/root/vi/glassfish6/glassfish/modules/jersey-media-json-binding.jar:/root/vi/glassfish6/glassfish/modules/jersey-server.jar:/root/vi/glassfish6/glassfish/modules/jersey-container-servlet.jar:/root/vi/glassfish6/glassfish/modules/jersey-container-servlet-core.jar:/root/vi/glassfish6/glassfish/modules/guava.jar:/root/vi/glassfish6/glassfish/modules/jakarta.el.jar:/root/vi/glassfish6/glassfish/modules/tyrus-websocket-core.jar:/root/vi/glassfish6/glassfish/modules/tyrus-client.jar:/root/vi/glassfish6/glassfish/modules/tyrus-core.jar:/root/vi/glassfish6/glassfish/modules/tyrus-container-grizzly.jar:/root/vi/glassfish6/glassfish/modules/tyrus-container-grizzly-client.jar:/root/vi/glassfish6/glassfish/modules/glassfish-grizzly-extra-all.jar:/root/vi/glassfish6/glassfish/modules/nucleus-grizzly-all.jar:/root/vi/glassfish6/glassfish/modules/tyrus-server.jar:/root/vi/glassfish6/glassfish/modules/tyrus-container-servlet.jar:/root/vi/glassfish6/glassfish/modules/tyrus-spi.jar:/root/vi/glassfish6/glassfish/modules/com.ibm.jbatch-runtime-all.jar:/root/vi/glassfish6/glassfish/modules/com.ibm.jbatch-ri-spi.jar:/root/vi/glassfish6/glassfish/modules/glassfish-batch-connector.jar:/root/vi/glassfish6/glassfish/modules/glassfish-batch-commands.jar:/root/vi/glassfish6/glassfish/modules/yasson.jar:/root/vi/glassfish6/glassfish/modules/javamail-connector.jar:/root/vi/glassfish6/glassfish/modules/javamail-runtime.jar:/root/vi/glassfish6/glassfish/modules/jakarta.websocket-api.jar:/root/vi/glassfish6/glassfish/modules/jakarta.enterprise.concurrent-api.jar:/root/vi/glassfish6/glassfish/modules/jakarta.batch-api.jar:/root/vi/glassfish6/glassfish/modules/jakarta.enterprise.cdi-api.jar:/root/vi/glassfish6/glassfish/modules/jakarta.xml.ws-api.jar:/opt/lib/tools.jar:/root/jakartaeetck/classes:/root/jakartaeetck/src/com/sun/ts/tests/webservices12/ejb/annotations/WSEjbWebServiceRefWithNoDDsTest -wsdl:soap1.1 -r /root/jakartaeetck/src/com/sun/ts/tests/webservices12/ejb/annotations/WSEjbWebServiceRefWithNoDDsTest com.sun.ts.tests.webservices12.ejb.annotations.WSEjbWebServiceRefWithNoDDsTest.WSEjbWSRefWithNoDDsTestHelloEJB
   [runcts] OUT =>     [wsgen] Error: Could not find or load main class com.sun.tools.ws.WsGen
   [runcts] OUT =>     [wsgen] Caused by: java.lang.ClassNotFoundException: com.sun.tools.ws.WsGen
   [runcts] OUT => [dosubdirs] The following error occurred while executing this line:
   [runcts] OUT => [dosubdirs] /root/jakartaeetck/src/com/sun/ts/tests/webservices12/ejb/annotations/WSEjbWebServiceRefWithNoDDsTest/build.xml:35: The following error occurred while executing this line:
   [runcts] OUT => [dosubdirs] /root/jakartaeetck/src/com/sun/ts/tests/jaxws/common/xml/common.xml:1146: The following error occurred while executing this line:
   [runcts] OUT => [dosubdirs] /root/jakartaeetck/src/com/sun/ts/tests/jaxws/common/xml/common.xml:969: wsgen failed
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:571)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:440)
   [runcts] OUT => [dosubdirs] 	at com.sun.ant.taskdefs.common.DoSubdirs.execute(DoSubdirs.java:123)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
   [runcts] OUT => [dosubdirs] 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
   [runcts] OUT => [dosubdirs] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [runcts] OUT => [dosubdirs] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.Task.perform(Task.java:350)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.Target.execute(Target.java:449)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
   [runcts] OUT => [dosubdirs] 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
   [runcts] OUT => [dosubdirs] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [runcts] OUT => [dosubdirs] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.Task.perform(Task.java:350)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.Target.execute(Target.java:449)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.Main.runBuild(Main.java:830)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.Main.startAnt(Main.java:223)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
   [runcts] OUT => [dosubdirs] Caused by: /root/jakartaeetck/src/com/sun/ts/tests/webservices12/ejb/annotations/WSEjbWebServiceRefWithNoDDsTest/build.xml:35: The following error occurred while executing this line:
   [runcts] OUT => [dosubdirs] /root/jakartaeetck/src/com/sun/ts/tests/jaxws/common/xml/common.xml:1146: The following error occurred while executing this line:
   [runcts] OUT => [dosubdirs] /root/jakartaeetck/src/com/sun/ts/tests/jaxws/common/xml/common.xml:969: wsgen failed
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:571)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:440)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:106)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
   [runcts] OUT => [dosubdirs] 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
   [runcts] OUT => [dosubdirs] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [runcts] OUT => [dosubdirs] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.Task.perform(Task.java:350)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.Target.execute(Target.java:449)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
   [runcts] OUT => [dosubdirs] 	... 29 more
   [runcts] OUT => [dosubdirs] Caused by: /root/jakartaeetck/src/com/sun/ts/tests/jaxws/common/xml/common.xml:1146: The following error occurred while executing this line:
   [runcts] OUT => [dosubdirs] /root/jakartaeetck/src/com/sun/ts/tests/jaxws/common/xml/common.xml:969: wsgen failed
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:571)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:394)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
   [runcts] OUT => [dosubdirs] 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
   [runcts] OUT => [dosubdirs] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [runcts] OUT => [dosubdirs] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.Task.perform(Task.java:350)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.Target.execute(Target.java:449)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
   [runcts] OUT => [dosubdirs] 	... 42 more
   [runcts] OUT => [dosubdirs] Caused by: /root/jakartaeetck/src/com/sun/ts/tests/jaxws/common/xml/common.xml:969: wsgen failed
   [runcts] OUT => [dosubdirs] 	at com.sun.tools.ws.ant.WsTask2.execute(WsTask2.java:466)
   [runcts] OUT => [dosubdirs] 	at com.sun.tools.ws.ant.WsGenBase.execute(WsGenBase.java:338)
   [runcts] OUT => [dosubdirs] 	at com.sun.tools.ws.ant.WsGen.execute(WsGen.java:77)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
   [runcts] OUT => [dosubdirs] 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
   [runcts] OUT => [dosubdirs] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [runcts] OUT => [dosubdirs] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.Task.perform(Task.java:350)
   [runcts] OUT => [dosubdirs] 	at java.base/java.util.Vector.forEach(Vector.java:1387)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)
   [runcts] OUT => [dosubdirs] 	at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:217)
   [runcts] OUT => [dosubdirs] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   [runcts] OUT => [dosubdirs] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   [runcts] OUT => [dosubdirs] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [runcts] OUT => [dosubdirs] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:155)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
   [runcts] OUT => [dosubdirs] 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
   [runcts] OUT => [dosubdirs] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [runcts] OUT => [dosubdirs] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.Task.perform(Task.java:350)
   [runcts] OUT => [dosubdirs] 	at java.base/java.util.Vector.forEach(Vector.java:1387)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)
   [runcts] OUT => [dosubdirs] 	at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:197)
   [runcts] OUT => [dosubdirs] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   [runcts] OUT => [dosubdirs] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   [runcts] OUT => [dosubdirs] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [runcts] OUT => [dosubdirs] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:155)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
   [runcts] OUT => [dosubdirs] 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
   [runcts] OUT => [dosubdirs] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [runcts] OUT => [dosubdirs] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.Task.perform(Task.java:350)
   [runcts] OUT => [dosubdirs] 	at java.base/java.util.Vector.forEach(Vector.java:1387)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
   [runcts] OUT => [dosubdirs] 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
   [runcts] OUT => [dosubdirs] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [runcts] OUT => [dosubdirs] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.Task.perform(Task.java:350)
   [runcts] OUT => [dosubdirs] 	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:391)
   [runcts] OUT => [dosubdirs] 	... 54 more
   [runcts] OUT => [dosubdirs] BUILD FAILED
   [runcts] OUT => [dosubdirs] The following directories failed:
   [runcts] OUT => [dosubdirs] /root/jakartaeetck/bin/xml/../../src/com/sun/ts/tests/webservices12/ejb/annotations/WSEjbWebServiceRefWithNoDDsTest
   [runcts] OUT => [dosubdirs] 
```

**Comment by hussainnm** [comment]
Setting `fork="false"` in the `wsgen` task makes it work by inheriting the classpath from ant environment. When `fork="true"` in JDK11 setting utilizes the MR classes in webservices-osgi.jar which is not setting the classpath for the fork. Hence the `java.lang.ClassNotFoundException: com.sun.tools.ws.WsGen` is thrown. Either fork should be set to false to inherit the ant classloader or the `java.class.path` system property should be passed with a proper classpath.

**Comment by gurunrao** [comment]
> Setting `fork="false"` in the `wsgen` task makes it work by inheriting the classpath from ant environment. When `fork="true"` in JDK11 setting utilizes the MR classes in webservices-osgi.jar which is not setting the classpath for the fork. Hence the `java.lang.ClassNotFoundException: com.sun.tools.ws.WsGen` is thrown. Either fork should be set to false to inherit the ant classloader or the `java.class.path` system property should be passed with a proper classpath.

since we applied fork="false", PR https://github.com/eclipse-ee4j/jakartaee-tck/pull/676, should also work for ^ issue.

**Comment by hussainnm** [comment]
Yes, #676 fixes this issues. Closing this issue.
