### ISSUE TITLE
Standalone TCK tests all fail -No value found for jimage.dir

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/jakartaee-tck#754]
**Describe the bug**
Running the standalone TCK tests on https://ci.eclipse.org/jakartaee-tck all fail.

E.g. https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1521/

**To Reproduce**
1. Go to https://ci.eclipse.org/jakartaee-tck/job/eftl-standalonetck-certification/ then https://ci.eclipse.org/jakartaee-tck/job/eftl-standalonetck-certification/build?delay=0sec
2. Click on Build
3. Go to https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/ and then https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1521/execution/node/218/log/?consoleFull

**Expected behavior**
At least tests all running and probably all passing.

**Screenshots**
```
[javatest.batch] com.sun.ts.lib.deliverable.PropertyNotSetException: No value found for jimage.dir.  Please check your jte file for an appropiate value
[javatest.batch] 	at com.sun.ts.lib.deliverable.AbstractPropertyManager.getProperty(AbstractPropertyManager.java:214)
[javatest.batch] 	at com.sun.ts.lib.harness.TSScript.run(TSScript.java:237)
[javatest.batch] 	at com.sun.javatest.Script.run(Script.java:241)
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Safari
 - Version: 15

**Smartphone (please complete the following information):**
 - Device: iPhone6 to iPhone12
 - OS: e.g. iOS8.1 to iOS 15
 - Browser Safari
 - Version 15

**Additional context**
I think a value for `jimage.dir` needs to be set to something. The tests really like to have this, and without it they all fail.

**Comment by scottmarlow** [comment]
Either try setting a value for `jimage.dir` (perhaps default it to `/tmp/jimagedir` or something like that.  The other thing to try would be removing the references to the `jimage.dir` variable for signature testing.

**Comment by scottmarlow** [comment]
@arjantijms should I start an email thread to see if we can get a volunteer to help solve this?  I would like to help others that might not actively work on issues like this, to have a chance to be coached through solving problems like this.

**Comment by arjantijms** [comment]
> Either try setting a value for jimage.dir

Where would be the best place to set that? But perhaps the real question is, why does it suddenly start asking for that? A few weeks ago those jobs were still running fine AFAIK.

**Comment by scottmarlow** [comment]
Good point, I will check.

**Comment by scottmarlow** [comment]
Looks like we need to revert the removal of `jimage.dir` in https://github.com/eclipse-ee4j/jakartaee-tck/pull/738.  I thought we didn't need jimage anymore but we need to either remove it completely and test or put it back in the ts.jte files.

**Comment by gurunrao** [comment]
> Looks like we need to revert the removal of `jimage.dir` in #738. I thought we didn't need jimage anymore but we need to either remove it completely and test or put it back in the ts.jte files.

PR #738 - adds jimage dir to ts.jte(since we have made ts.jte.jdk11 as ts.jte).

**Comment by gurunrao** [comment]
> **Describe the bug** Running the standalone TCK tests on https://ci.eclipse.org/jakartaee-tck all fail.
> 
> E.g. https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1521/
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to https://ci.eclipse.org/jakartaee-tck/job/eftl-standalonetck-certification/ then https://ci.eclipse.org/jakartaee-tck/job/eftl-standalonetck-certification/build?delay=0sec
> 2. Click on Build
> 3. Go to https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/ and then https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1521/execution/node/218/log/?consoleFull
> 4. See error
> 
> **Expected behavior** At least tests all running and probably all passing.
> 
> **Screenshots**
> 
> ```
> [javatest.batch] com.sun.ts.lib.deliverable.PropertyNotSetException: No value found for jimage.dir.  Please check your jte file for an appropiate value
> [javatest.batch] 	at com.sun.ts.lib.deliverable.AbstractPropertyManager.getProperty(AbstractPropertyManager.java:214)
> [javatest.batch] 	at com.sun.ts.lib.harness.TSScript.run(TSScript.java:237)
> [javatest.batch] 	at com.sun.javatest.Script.run(Script.java:241)
> ```
> 
> **Desktop (please complete the following information):**
> 
> * OS: Linux
> * Browser: Safari
> * Version: 15
> 
> **Smartphone (please complete the following information):**
> 
> * Device: iPhone6 to iPhone12
> * OS: e.g. iOS8.1 to iOS 15
> * Browser Safari
> * Version 15
> 
> **Additional context** I think a value for `jimage.dir` needs to be set to something. The tests really like to have this, and without it they all fail.

Certification Job are for testing promoted/staged bundles(once test runs are stable), currently there are no staged/promoted bundles for Jakarta EE 10. Old certification jobs (used above) are using run scripts modified for Jakarta EE 10 (PR #738) and  Jakarta EE 9.1 TCK bundles, which is not correct way to test TCK bundles.
We should use Jobs from https://ci.eclipse.org/jakartaee-tck/job/10/ [Jakarta EE 10 TCK jobs]. We can verify with Certification jobs, post TCK bundles are promoted/staged.

**Comment by scottmarlow** [comment]
Closing since the pr was merged and https://ci.eclipse.org/jakartaee-tck/blue/organizations/jenkins/jakartaee-tck/detail/master/1524/pipeline/65/ passed!
