### ISSUE TITLE
[jdk18][security-manager] running TCK on SE 18 leads to UnsupportedOperationException

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jakartaee-tck#904]
**Describe the bug**

**To Reproduce**
* set up Java SE 18
* remove security manager related options from the `command.testExecute` prop in `ts.jte` (ie like in 
[ca.ts.jte](https://github.com/eclipse-ee4j/jakartaee-tck/files/8322872/ca.ts.jte.txt))
* run the TCK

=> fails with"
```
runclient:
[javatest.batch] java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
[javatest.batch] 	at java.base/java.lang.System.setSecurityManager(System.java:416)
[javatest.batch] 	at com.sun.javatest.JavaTestSecurityManager.install(JavaTestSecurityManager.java:84)
[javatest.batch] 	at com.sun.javatest.tool.Main.run(Main.java:291)
[javatest.batch] 	at com.sun.javatest.tool.Main.main0(Main.java:150)
[javatest.batch] 	at com.sun.javatest.tool.Main.main(Main.java:130)
```

**Expected behavior**
tests are executed

**Comment by starksm64** [comment]
SecurityManger has been dropped for EE 11.
