### ISSUE TITLE
1001 test failures in Faces TCK on Glassfish 7

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/jakartaee-tck#913]
**Describe the bug**
The Faces standalone TCK when run with Glassfish 7 latest nightly has 1001 test failures out of total 5430 tests.

**To Reproduce**
```
git clone https://github.com/jakartaee/faces.git
cd faces/tck/faces-tck ; mvn clean verify 
```
1001 tests are failing now.

**Expected behavior**
All tests should pass. 

**Additional context**
This task is part of https://github.com/jakartaee/faces/issues/1600 to produce new Faces TCK bundle where the faces tck from jakartaee-tck will be integrated.

server logs from local run : 
[1_server.log](https://github.com/eclipse-ee4j/jakartaee-tck/files/8374189/1_server.log)
[2_server.log](https://github.com/eclipse-ee4j/jakartaee-tck/files/8374321/2_server.log)
[3_server.log](https://github.com/eclipse-ee4j/jakartaee-tck/files/8374813/3_server.log)

Test run pipeline job : 
https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1713/

Test run logs: 
https://ci.eclipse.org/jakartaee-tck/blue/rest/organizations/jenkins/pipelines/jakartaee-tck/branches/master/runs/1713/nodes/63/steps/199/log/?start=0

Update : The TCK has been migrated to [faces](https://github.com/jakartaee/faces) hence the fixes will need to go to that repo.

@arjantijms @BalusC @scottmarlow

**Comment by alwin-joseph** [comment]
The server logs has exceptions of type below : 

1. 
```
java.lang.NullPointerException
    at jakarta.faces.component.UIComponentBase.getRenderer(UIComponentBase.java:1047)
    at jakarta.faces.component.UIComponentBase.encodeBegin(UIComponentBase.java:529)
    at com.sun.ts.tests.jsf.api.jakarta_faces.component.common.BaseUIComponentTestServlet.uiComponentEncodeBeginTest(BaseUIComponentTestServlet.java:3722)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at com.sun.ts.tests.jsf.common.servlets.HttpTCKServlet.invokeTest(HttpTCKServlet.java:163)
    at com.sun.ts.tests.jsf.common.servlets.HttpTCKServlet.doGet(HttpTCKServlet.java:104)

```

Probable cause at encodeBegin: getFacesContext() is null ?
```
UIComponent comp = createComponent();
comp.encodeBegin(getFacesContext());
```

2. 
```
com.sun.faces.application.view.ViewHandlingStrategyNotFoundException
        at java.base/java.util.Optional.orElseThrow(Optional.java:408)
        at com.sun.faces.application.view.ViewHandlingStrategyManager.getStrategy(ViewHandlingStrategyManager.java:57)
        at com.sun.faces.application.view.ViewDeclarationLanguageFactoryImpl.getViewDeclarationLanguage(ViewDeclarationLanguageFactoryImpl.java:45)
        at com.sun.faces.application.view.MultiViewHandler.createView(MultiViewHandler.java:145)
        at jakarta.faces.application.ViewHandlerWrapper.createView(ViewHandlerWrapper.java:110)
        at jakarta.faces.application.ViewHandlerWrapper.createView(ViewHandlerWrapper.java:110)
        at com.sun.ts.tests.jsf.api.jakarta_faces.application.viewhandlerwrapper.TestServlet.viewHandlerCreateViewTest(TestServlet.java:105)
```

Probable cause: context is null ?
```
FacesContext context = getFacesContext();
UIViewRoot root = getApplication().getViewHandler().createView(context,
        "/root");
```

3. 

```
StandardWrapperValve[TestServlet]: Servlet.service() for servlet TestServlet threw exception
      java.lang.NullPointerException
              at jakarta.faces.component.UIComponentBase.getRenderer(UIComponentBase.java:1047)
              at jakarta.faces.component.UIComponentBase.decode(UIComponentBase.java:498)
              at jakarta.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:872)
              at jakarta.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:867)
              at jakarta.faces.component.UIViewRoot.processDecodes(UIViewRoot.java:997)
              at com.sun.ts.tests.jsf.api.jakarta_faces.component.behavior.ajax.TestServlet.ajaxBehaviorBroadcastTest(TestServlet.java:87)
```

Probable cause : context is null ?
```
FacesContext context = getFacesContext();
root.processDecodes(context);
```

4. 
```
java.lang.InstantiationException: org.jboss.weld.module.jsf.ConversationAwareViewHandler
      at java.base/java.lang.Class.newInstance(Class.java:571)
      at com.sun.ts.tests.jsf.common.util.JSFTestUtil.checkForNPE(JSFTestUtil.java:440)
      at com.sun.ts.tests.jsf.api.jakarta_faces.application.viewhandler.TestServlet.viewHandlerCalculateLocaleNPETest(TestServlet.java:264)
...
Caused by: java.lang.NoSuchMethodException: org.jboss.weld.module.jsf.ConversationAwareViewHandler.<init>()
```
Probable cause at : 

```
JSFTestUtil.checkForNPE(getApplication().getViewHandler().getClass(),
        "calculateLocale", new Class<?>[] { FacesContext.class },
        new Object[] { null }, out);
```

5. 
```
StandardWrapperValve[TestServlet]: Servlet.service() for servlet TestServlet threw exception
java.lang.NullPointerException: Argument Error: Parameter renderKitId is null
      at com.sun.faces.renderkit.RenderKitFactoryImpl.getRenderKit(RenderKitFactoryImpl.java:78)
      at com.sun.ts.tests.jsf.api.jakarta_faces.component.common.BaseUIComponentTestServlet.uiComponentGetRendersChildrenTest(BaseUIComponentTestServlet.java:1997)
      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.base/java.lang.reflect.Method.invoke(Method.java:566)
      at com.sun.ts.tests.jsf.common.servlets.HttpTCKServlet.invokeTest(HttpTCKServlet.java:163)
```

Probable cause at : getRenderKitId() is null
```
RenderKitFactory renderKitFactory = (RenderKitFactory) FactoryFinder
            .getFactory(FactoryFinder.RENDER_KIT_FACTORY);
RenderKit renderKit = renderKitFactory.getRenderKit(getFacesContext(),
            getFacesContext().getViewRoot().getRenderKitId())
```

**Comment by arjantijms** [comment]
> The Faces standalone TCK when run with Glassfish 7 (M2 - latest) has 1001 test failures out of total 5430 tests.

Do you mean "M2, which is the latest" or "from M2 to the latest"?

Regardless, the latest nightly https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1718/ has 1001 failures too.

**Comment by alwin-joseph** [comment]
> 



> > The Faces standalone TCK when run with Glassfish 7 (M2 - latest) has 1001 test failures out of total 5430 tests.
> 
> Do you mean "M2, which is the latest" or "from M2 to the latest"?
> 
> Regardless, the latest nightly https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1718/ has 1001 failures too.

I meant M2 which is the latest, which is not(corrected)! 
The local run having server logs was done using M2 ; the CI jobs used latest nightly. Both have same failures.

**Comment by arjantijms** [comment]
> I meant M2 which is the latest, which is not(corrected)!

Thanks for the clarification. We also had an error in the script that pushes out the nightlies, so until yesterday the nightly was also still M2.
